Support and facilitate converting text to paths
tscircuit/schematic-symbols pull request #114
Opened 2024-10-03 22:41 UTC by Timer00

> A **path text** is text that was converted to paths using a tool such as inkscape. 

### Problem

Rendering text within an SVG may cause issues since text can be rendered differently in different contexts. 

### Solution

Render text as regular paths within our SVGs.

### PR Objectives

- [x] Consistent and readable rendering of path texts
- [ ] Little to no changes in current symbol creation flow for Symbols that include text

2024-10-03 22:42 UTC, Timer00 commented
### Current status
After considerable tweaking I found a way to render path texts in a readable and somewhat consistent representation. However, this rendering requires modifying the strokeWidth, fill and closed properties of only the text paths.
So currently I am looking into ways we could detect that a path coming from inkscape was originally text, and then apply the correct styling.

2024-10-05 00:49 UTC, Timer00 commented
> ### Current status
> After considerable tweaking between code and inkscape I found a way to render path texts in a readable and somewhat consistent representation. However, this rendering requires modifying the strokeWidth, fill and closed properties of only the text paths. So currently I am looking into ways we could detect that a path coming from inkscape was originally text, and then apply the correct styling.
> 
> If you have any other ideas feel free to let me know!

I've solved this challenge by integrating the inkscape:label into our Primitives and implementing an extension for batch labeling + another for flattening groups recursively [wip] in inkscape.

2024-10-05 00:54 UTC, Timer00 commented
Will remove text sample once approved.

2024-10-05 00:55 UTC, seveibar commented on generated/symbols-index.ts
> +  "text_paths_sample_vert": _text_paths_sample_vert,
we can use a snapshot test outside of the regular symbols definitions using https://github.com/tscircuit/bun-match-svg, that way this doesn't increase bundle size for symbols or get mixed in with electrical symbols

2024-10-05 00:56 UTC, seveibar commented on scripts/inkscape/organize_svg.py
> +    OrganizeSVG().run()
i appreciate the effort on this one, but doesn't it make more sense to convert svg text to paths automatically if they aren't {REF} or {VAL} in typescript? The maintainability of python in a ts repo is low

2024-10-05 00:59 UTC, seveibar requested changes
absolutely awesome feature but i'd like to remove inkscape as a dependency rather than bake it in so closely, also having python in this repo is likely to decrease maintainability (although ai generally helps to keep maintainability high)

I think we could just as easily do this in Typescript for non-reference text. We already have a custom alphabet defined for PCBs here: https://github.com/tscircuit/pcb-viewer/blob/main/src/assets/alphabet.ts which we could isolate into a dedicated module if need be

2024-10-05 01:00 UTC, seveibar commented
RE: alphabet, if that is useful we can literally just copy it over for now.

2024-10-05 01:05 UTC, seveibar commented
just watched the video. It's kind of interesting because I can definitely see us having inkscape extensions to improve inkscape workflows. It makes a lot of sense, but it also kind of creates this extra knowledge layer/tooling dependency vs doing it programmatically for non-reference text.

But a quick comment on the video: ABSOLUTELY AWESOME. Tutorial videos are a huge value add

2024-10-05 13:28 UTC, Timer00 commented
> absolutely awesome feature but i'd like to remove inkscape as a dependency rather than bake it in so closely, also having python in this repo is likely to decrease maintainability (although ai generally helps to keep maintainability high)
> 
> I think we could just as easily do this in Typescript for non-reference text. We already have a custom alphabet defined for PCBs here: https://github.com/tscircuit/pcb-viewer/blob/main/src/assets/alphabet.ts which we could isolate into a dedicated module if need be

oh man! I had this same idea but thought it would be too much work to create a whole alphabet. That definitely makes it easier and this solutions is way less hassle for our fellow contributors. Will def work on that soon!

2024-10-05 22:40 UTC, Timer00 commented
One thought that occurred to me is that this could still be useful for converting any UTF-8 character to a path.

2024-10-07 21:09 UTC, seveibar commented
yea i think we could do the conversion in this module, or import it as an npm module. We should have some snapshot testing on it to make sure it's good.

(I think it might be better to implement inside this module vs externally to make things easier for contributors if there's a bug)

2024-11-17 02:09 UTC, closed without merging