add 4 pin crystal symbol
tscircuit/schematic-symbols pull request #210
Opened 2024-11-19 18:07 UTC by ni9999

fixes #202 
/claim #202

2024-11-19 22:00 UTC, seveibar requested changes
nice work, anchors aren't quite right in either view. Make sure the text grows away from the symbol. These texts are replaced with potentially very long names so they must be anchored properly

Use `modifySymbol` it's a better, more modern api

![image](https://github.com/user-attachments/assets/04fae7a9-9a6b-492e-9579-f745c93f4ce7)

2024-11-19 22:00 UTC, seveibar commented on symbols/crystal_4pin_horz.ts
> +})
use `modifySymbol` instead

please label pins 2 and 4 "gnd1", "gnd2"

2024-11-19 22:00 UTC, seveibar commented
@ni9999 nice work, was happy to see this

2024-11-20 16:16 UTC, ni9999 commented on symbols/crystal_4pin_horz.ts
> +})
@seveibar changed accordingly.

2024-11-23 20:55 UTC, seveibar commented on symbols/crystal_4pin_horz.ts
> +  .labelPort("bottom1", ["gnd2"])
```suggestion
  .labelPort("top1", ["2", "gnd1"])
  .labelPort("bottom1", ["4", "gnd2"])
```

2024-11-23 20:56 UTC, seveibar requested changes
@ni9999, just accept my suggestion and regenerate the snapshot, and you're good to go!!!

2024-11-24 01:39 UTC, ni9999 commented
@seveibar accepted but now gnd1 and gnd2 is gone
![crystal_4pin_horz](https://github.com/user-attachments/assets/5678b319-61b3-431d-9f76-22575e408308)

2024-11-24 02:02 UTC, seveibar approved these changes
Yes theyre now alias rather than primary labels, we should show all the labels but it would be crowded 🤷

2024-11-27 07:56 UTC, seveibar commented
@ni9999 im eager to merge this but it has conflicts!

2024-12-12 06:33 UTC, merged