Fix #213 feat: Add missing snapshot validation to prevent ungenerated snapshots
tscircuit/schematic-symbols pull request #214
Opened 2024-11-22 00:11 UTC by nocodeventure-nl

This PR adds validation to ensure all symbols have corresponding snapshots generated. This helps prevent issues where developers might forget to generate snapshots for newly added symbols.

Changes:
- Modified snapshot test to check for missing snapshots before running tests
- Added clear error message guiding developers to run `bun run test` when snapshots are missing
- Updated README with clearer instructions about snapshot generation requirement

This change will help catch missing snapshots earlier in the development process and provide clearer guidance on how to fix the issue.

/claim #213

2024-11-22 00:28 UTC, nocodeventure-nl commented
error: Missing snapshot for symbol "ac_voltmeter_horz". Please run "bun run test" to generate snapshots.
      at C:\Users\Software Buddy\OneDrive\Documenten\commercial\bounties\schematic-symbols\tests\snapshot-svg.test.ts:28:13
✗ Snapshot test for all SVG symbols

 3 pass
 1 fail
 3 expect() calls
Ran 4 tests across 2 files.

2024-11-22 00:37 UTC, nocodeventure-nl commented
@seveibar Additionally, we can automatically generate the snapshot and run "bun test' if snapshots are absent. What are your thoughts on this approach?

2024-11-22 06:04 UTC, imrishabh18 reviewed
@nocodeventure-nl Can you remove the `package-lock.json` from the PR pls? And then take a look at the failing test case

2024-11-22 14:40 UTC, nocodeventure-nl commented
> @nocodeventure-nl Can you remove the `package-lock.json` from the PR pls? And then take a look at the failing test case

Done the package lock is removed.

2024-11-22 15:53 UTC, nocodeventure-nl commented
> Can you fix the failing test? Check the workflow

@imrishabh18 We're not so familiar with the repo and run bun test fails to generate the symbol. Although we can see it exists?

2024-11-22 21:54 UTC, seveibar commented
@nocodeventure-nl you may need to run `BUN_UPDATE_SNAPSHOTS=1 bun test path/to/failing/test.ts` to update your snapshot

2024-11-22 21:54 UTC, seveibar commented on tests/snapshot-svg.test.ts
> +    if (!snapshotExists) {
if `BUN_UPDATE_SNAPSHOTS=1` you should still run

2024-11-22 22:19 UTC, nocodeventure-nl commented
@seveibar We kept ranning into issues and generated a way for the snapshots to be created automatically when running bun run test and made some other changes to improve the experience.

1. Created a new script `generate-snapshots.ts` that:
   - Generates SVG snapshots for all symbols
   - Creates the snapshots directory if it doesn't exist
   - Writes snapshots in the correct format for testing

2. Modified `snapshot-svg.test.ts` to:
   - Check for existing snapshots
   - Generate missing snapshots automatically instead of failing
   - Provide helpful console output when generating new snapshots

3. Updated `package.json` with:
   - New `snapshots` script to generate snapshots independently
   - Modified `test` script to run snapshots generation before testing

- When adding new symbols:
  1. The test system automatically detects missing snapshots
  2. Instead of failing, it generates new snapshots for those symbols
  3. Validates the generated snapshots

- Developers can:
  - Run `bun run snapshots` to generate/update all snapshots
  - Run `bun test` to validate against existing snapshots
  - Run `bun run test` to do both build and test with snapshot generation

The system now handles new symbols gracefully instead of requiring manual snapshot generation.

2024-11-22 22:23 UTC, seveibar requested changes
I dont really understand whats happening here because source code was generated. Look at the bun-match-svg module, in our projects we use BUN_UPDATE_SNAPSHOTS to update snapshots. It looks like you generated some source code, and youve still committed a package lock file

2024-11-22 22:32 UTC, nocodeventure-nl commented
> I dont really understand whats happening here because source code was generated. Look at the bun-match-svg module, in our projects we use BUN_UPDATE_SNAPSHOTS to update snapshots. It looks like you generated some source code, and youve still committed a package lock file

Thanks for pointing that out. I removed the package lock. Having a look at the source code now.

2024-11-27 09:35 UTC, melmathari commented
@imrishabh18 Failing tests have been addressed.

2024-12-03 02:09 UTC, closed without merging