add opamp symbol
tscircuit/schematic-symbols pull request #231
Opened 2024-12-29 08:38 UTC by techmannih

/claim #230 
fixes #230

2024-12-29 15:32 UTC, ShiboSoftwareDev requested changes
can you draw the plus/minus signs? like in the issue

looks like the pins are not straight:
![image](https://github.com/user-attachments/assets/61c1019a-8e19-4ce1-a7dd-f02dc6a5995a)

2024-12-29 15:50 UTC, Abse2001 commented
@techmannih add the + - to the symbol as Seve's symbol in the issue
![image](https://github.com/user-attachments/assets/1d990b0e-5970-44ab-bef8-6c08f954abae)
the capacitor_polarized has + sign
![image](https://github.com/user-attachments/assets/30a7a3d2-cdb0-449c-919f-bbe4096e6839)

2024-12-29 20:04 UTC, ShiboSoftwareDev requested changes
a couple of changes:
- see how the text will overlap with the symbol? maybe make the anchor to the left or just move the text up, whichever looks best
- generate an up/down/left/right orientation like the other symbols
- make the symbol wider (check Seve's screenshot)
- the + - signs are too bold imo maybe reduce the lines width
![image](https://github.com/user-attachments/assets/fdaeeb52-51ff-4f7c-9f18-f8fa7431cffc)

2024-12-30 04:30 UTC, seveibar commented
Yea we really only want up/down/left/right, no need to do horizontal and vertical

2024-12-31 07:23 UTC, Anshgrover23 reviewed
@seveibar @ShiboSoftwareDev if i am not wrong this is the correct symbol for opamp.

![image](https://github.com/user-attachments/assets/41c228e7-bf3b-4109-8253-f05359a0ec7b)

2024-12-31 20:15 UTC, seveibar commented
we should make both symbols, one can be called `opamp_with_power` and the other can be called `opamp_no_power`

2024-12-31 20:15 UTC, seveibar commented
nice catch @Anshgrover23

2025-01-01 05:20 UTC, ShiboSoftwareDev commented
> a couple of changes:
> 
> * see how the text will overlap with the symbol? maybe make the anchor to the left or just move the text up, whichever looks best
> * generate an up/down/left/right orientation like the other symbols
> * the symbol could be wider as per the issue ss
> * the + - signs are too bold imo maybe reduce the lines width

https://github.com/tscircuit/schematic-symbols/pull/231#pullrequestreview-2524999891

2025-01-01 05:30 UTC, Anshgrover23 requested changes
CC: @seveibar like what is the correct sign on this opamp? like one is inverting and one is non-inverting so in snapshots of both symbols it is different.
![image](https://github.com/user-attachments/assets/6d67ecc8-d1fb-4a90-ad54-47b60e23aff8)

2025-01-04 16:40 UTC, seveibar commented
@techmannih great work

https://tscircuit.slack.com/files/U05FQPWERFZ/F0879PBUX51/screenshare_-_2025-01-04_8_39_42_am.webm?origin_team=T05G7PFE0DS&origin_channel=D06P5J945R9

2025-01-07 04:24 UTC, seveibar approved these changes

2025-01-07 05:08 UTC, merged